name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configurar CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.3.0'
    - name: Criar pasta build e configurar o CMake
      run: cmake -B build -S .
    - name: Compilar os testes
      run: cmake --build build --target SimplexTests
    - name: Executar os testes unitários
      run: ./build/SimplexTests
